# WAP to take input fron user eight numbers and display all the uniqe number (Once).
s = set()
n = input("Enter Number =")
s.add(int(n))
n = input("Enter Number =")
s.add(int(n))
n = input("Enter Number =")
s.add(int(n))
n = input("Enter Number =")
s.add(int(n))
n = input("Enter Number =")
s.add(int(n))
n = input("Enter Number =")
s.add(int(n))
n = input("Enter Number =")
s.add(int(n))
n = input("Enter Number =")
s.add(int(n))
print(s)