# create an dictionary . allow 4 frinds to enter  their favorite language as value and use key as their names. Assume that the names are unique.
d = {}
name = input("Enter frinds name : ")
lang = input("Enter language name : ")
d.update({name:  lang})
name = input("Enter frinds name : ")
lang = input("Enter language name : ")
d.update({name:  lang})
name = input("Enter frinds name : ")
lang = input("Enter language name : ")
d.update({name:  lang})
name = input("Enter frinds name : ")
lang = input("Enter language name : ")
d.update({name:  lang})
print(d)